config/routes.rb
InventoryManagement::Application.routes.draw do

  resources :private_orders

  resources :invoices

  resources :cart_items

  resources :orders

  resources :customers

	resources :artists

	resources :albums

	resources :users
	
	resources :public, :only => [:list, :show, :add_to_cart, :show_cart, :empty_cart, :remove_item, :checkout, :save_order, :report]
	resources :private, :only => [:list, :add_private_cart, :private_showcart, :remove_private_item, :empty_private_cart, :show_private_checkout, :save_private_order, :private_report]
	resources :sessions, :only => [:new, :create, :destroy]

	match '/', :to => 'pages#home'
	
	match '/signup', :to => 'users#new'
	match '/home', :to => 'users#home' 
	match '/testmail' => 'users#mail'
	
	match '/list', :to => 'public#list'
	match '/showalbum', :to => 'public#showalbum'
	match '/addtocart', :to => 'public#add_to_cart'
	match '/showcart', :to => 'public#show_cart'
	match '/emptycart', :to => 'public#empty_cart'
	match '/removeitem', :to => 'public#remove_item'
	match '/checkout', :to => 'public#checkout'
  match '/saveorder', :to => 'public#save_order'
  match '/report', :to => 'public#report'
	
  match '/privatealbums', :to => 'private#list'
  match '/addprivatecart', :to => 'private#add_private_cart'
  match '/privateshowcart', :to => 'private#private_showcart'
  match '/removeprivateitem', :to => 'private#remove_private_item'
  match '/emptyprivatecart', :to => 'private#empty_private_cart'
  match '/privatecheckout', :to => 'private#private_checkout'
  match '/showprivatecheckout', :to => 'private#show_private_checkout'
  match '/saveprivateorder', :to => 'private#save_private_order'
  match '/privatereport/:invoice' => 'private#private_report'

  
	match '/signin', :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'
	
	root :to => 'pages#home'
	
	
	

end

app/models/private_order.rb
class PrivateOrder < ActiveRecord::Base
    belongs_to :album
end

app/controllers/private_orders_controller.rb
class PrivateOrdersController < ApplicationController
  # GET /private_orders
  # GET /private_orders.xml
  def index
    @private_orders = PrivateOrder.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @private_orders }
    end
  end

  # GET /private_orders/1
  # GET /private_orders/1.xml
  def show
    @private_order = PrivateOrder.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @private_order }
    end
  end

  # GET /private_orders/new
  # GET /private_orders/new.xml
  def new
    @private_order = PrivateOrder.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @private_order }
    end
  end

  # GET /private_orders/1/edit
  def edit
    @private_order = PrivateOrder.find(params[:id])
  end

  # POST /private_orders
  # POST /private_orders.xml
  def create
    @private_order = PrivateOrder.new(params[:private_order])

    respond_to do |format|
      if @private_order.save
        format.html { redirect_to(@private_order, :notice => 'Private order was successfully created.') }
        format.xml  { render :xml => @private_order, :status => :created, :location => @private_order }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @private_order.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /private_orders/1
  # PUT /private_orders/1.xml
  def update
    @private_order = PrivateOrder.find(params[:id])

    respond_to do |format|
      if @private_order.update_attributes(params[:private_order])
        format.html { redirect_to(@private_order, :notice => 'Private order was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @private_order.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /private_orders/1
  # DELETE /private_orders/1.xml
  def destroy
    @private_order = PrivateOrder.find(params[:id])
    @private_order.destroy

    respond_to do |format|
      format.html { redirect_to(private_orders_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/private_orders_helper.rb
module PrivateOrdersHelper
end

app/views/private_orders/_form.html.erb
<%= form_for(@private_order) do |f| %>
  <% if @private_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@private_order.errors.count, "error") %> prohibited this private_order from being saved:</h2>

      <ul>
      <% @private_order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/private_orders/edit.html.erb
<h1>Editing private_order</h1>

<%= render 'form' %>

<%= link_to 'Show', @private_order %> |
<%= link_to 'Back', private_orders_path %>

app/views/private_orders/index.html.erb
<h1>Listing private_orders</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @private_orders.each do |private_order| %>
  <tr>
    <td><%= link_to 'Show', private_order %></td>
    <td><%= link_to 'Edit', edit_private_order_path(private_order) %></td>
    <td><%= link_to 'Destroy', private_order, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Private order', new_private_order_path %>

app/views/private_orders/new.html.erb
<h1>New private_order</h1>

<%= render 'form' %>

<%= link_to 'Back', private_orders_path %>

app/views/private_orders/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_private_order_path(@private_order) %> |
<%= link_to 'Back', private_orders_path %>