config/routes.rb
InventoryManagement::Application.routes.draw do

  resources :private_orders

  resources :invoices

  resources :cart_items

  resources :orders

  resources :customers

	resources :artists

	resources :albums

	resources :users
	
	resources :public, :only => [:list, :show, :add_to_cart, :show_cart, :empty_cart, :remove_item, :checkout, :save_order, :report]
	resources :private, :only => [:list, :add_private_cart, :private_showcart, :remove_private_item, :empty_private_cart, :show_private_checkout, :save_private_order, :private_report]
	resources :sessions, :only => [:new, :create, :destroy]

	match '/', :to => 'pages#home'
	
	match '/signup', :to => 'users#new'
	match '/home', :to => 'users#home' 
	match '/testmail' => 'users#mail'
	
	match '/list', :to => 'public#list'
	match '/showalbum', :to => 'public#showalbum'
	match '/addtocart', :to => 'public#add_to_cart'
	match '/showcart', :to => 'public#show_cart'
	match '/emptycart', :to => 'public#empty_cart'
	match '/removeitem', :to => 'public#remove_item'
	match '/checkout', :to => 'public#checkout'
  match '/saveorder', :to => 'public#save_order'
  match '/report', :to => 'public#report'
	
  match '/privatealbums', :to => 'private#list'
  match '/addprivatecart', :to => 'private#add_private_cart'
  match '/privateshowcart', :to => 'private#private_showcart'
  match '/removeprivateitem', :to => 'private#remove_private_item'
  match '/emptyprivatecart', :to => 'private#empty_private_cart'
  match '/privatecheckout', :to => 'private#private_checkout'
  match '/showprivatecheckout', :to => 'private#show_private_checkout'
  match '/saveprivateorder', :to => 'private#save_private_order'
  match '/privatereport/:invoice' => 'private#private_report'

  
	match '/signin', :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'
	
	root :to => 'pages#home'
	
	
	

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :orders
	
	
	validates :first_name, 	:presence => true
	validates :last_name, 	:presence => true
	validates :zip_code, 	:presence => true
	
	
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.xml
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.xml
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.xml
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.xml
  def create
    @customer = Customer.new(params[:customer])
 credit_card_number = params[:credit_card]
	@order = Order.new
	@cart = session[:cart]
	@order.line_items << @cart.items
	@customer.orders << @order
    
      if @customer.save
        redirect_to showcart_path
      else
        render :action => "new"
      end
    
  end

  # PUT /customers/1
  # PUT /customers/1.xml
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to(@customer, :notice => 'Customer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @customer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.xml
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to(customers_url) }
      format.xml  { head :ok }
    end
  end
  
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/checkout.html.erb
<h1>Music Library Store</h1>
<h2>Checkout</h2>
<% @cart = session[:cart] %>
<table style="width:500px; border-collapse:collapse;">
	<tr>
		<td>&nbsp;</td>
		<td>Album</td>
		<td>Artist</td>
		<td>Quantity</td>
		<td>Price</td>
	</tr>
	<% for item in @cart.items%>
		<% row_color=cycle("CCCCCC", "FFFFFF")%>
		<tr style="background: #<%= row_color%>;">
			<td valign="top" align='left' style='margin:0px;padding:0px;'><%= image_tag(item.album.image_path, :size => '20x20')%></td>
			<td valign="top" align='middle'>
				<p style="font-size:14px; font-weight:bold;margin:0px;padding:0px;"><%= item.album.title%></p>
			</td>
			<td valign="top" align='middle' style='margin:0px;padding:0px;'>
				<p style="font-size:12px; font-weight:bold;margin:0px;padding:0px;"><%= item.album.artist.name if item.album.artist%></p>
			</td>
			<td valign="top" align='middle' style='margin:0px;padding:0px;'>
				<p style="font-size:12px;margin:0px;padding:0px;"><%= item.quantity%></p>
			</td>
			<td valign="top" align='middle' style='margin:0px;padding:0px;'>
				<p style="font-size:12px;margin:0px;padding:0px;"><%= number_to_currency(item.price)%></p>
			</td>
		</tr>
	<% end %>
	<tr>
		<td>&nbsp;</td>
		<td>Shopping Cart Total</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td><%= number_to_currency(@cart.total_price)%></td>
	</tr>
</table>

<%= link_to('Continue Shopping', list_path)%>&nbsp; <br />
<br />
<%= form_for(@customer) do |f| %>
	<div class="field">
		<%= f.label :first_name %><br />
		<%= f.text_field :first_name %>
	</div>
	<div class="field">
		<%= f.label :last_name %><br />
		<%= f.text_field :last_name %>
	</div>
	<div class="field">
		<%= f.label :zip_code %><br />
		<%= f.text_field :zip_code %>
	</div>
	<div class="field">
		<%= f.label :credit_card %><br />
		<%= f.text_field :credit_card %>
	</div>
	<div class="actions">
		<%= f.submit "Place Order" %>
	</div>	
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @customers.each do |customer| %>
  <tr>
    <td><%= link_to 'Show', customer %></td>
    <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
    <td><%= link_to 'Destroy', customer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<% @cart = session[:cart]%>
<h1>New customer</h1>

<h1>Music Library Store</h1>
<h2>Checkout</h2>

<table style="width:500px; border-collapse:collapse;">
	<tr>
		<td>&nbsp;</td>
		<td>Album</td>
		<td>Artist</td>
		<td>Quantity</td>
		<td>Price</td>
	</tr>
	<% for item in @cart.items%>
		<% row_color=cycle("CCCCCC", "FFFFFF")%>
		<tr style="background: #<%= row_color%>;">
			<td valign="top" align='left' style='margin:0px;padding:0px;'><%= image_tag(item.album.image_path, :size => '20x20')%></td>
			<td valign="top" align='middle'>
				<p style="font-size:14px; font-weight:bold;margin:0px;padding:0px;"><%= item.album.title%></p>
			</td>
			<td valign="top" align='middle' style='margin:0px;padding:0px;'>
				<p style="font-size:12px; font-weight:bold;margin:0px;padding:0px;"><%= item.album.artist.name if item.album.artist%></p>
			</td>
			<td valign="top" align='middle' style='margin:0px;padding:0px;'>
				<p style="font-size:12px;margin:0px;padding:0px;"><%= item.quantity%></p>
			</td>
			<td valign="top" align='middle' style='margin:0px;padding:0px;'>
				<p style="font-size:12px;margin:0px;padding:0px;"><%= number_to_currency(item.price)%></p>
			</td>
		</tr>
	<% end %>
	<tr>
		<td>&nbsp;</td>
		<td>Shopping Cart Total</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td><%= number_to_currency(@cart.total_price)%></td>
	</tr>
</table>

<%= link_to('Continue Shopping', list_path)%>&nbsp; <br />
<br />
<%= form_for(@customer) do |f| %>
	<div class="field">
		<%= f.label :first_name %><br />
		<%= f.text_field :first_name %>
	</div>
	<div class="field">
		<%= f.label :last_name %><br />
		<%= f.text_field :last_name %>
	</div>
	<div class="field">
		<%= f.label :zip_code %><br />
		<%= f.text_field :zip_code %>
	</div>
	<div class="field">
		<%= f.label :credit_card %><br />
		<%= f.text_field :credit_card %>
	</div>
	<div class="actions">
		<%= f.submit "Place Order" %>
	</div>	
<% end %>
<form action='https://www.sandbox.paypal.com/cgi-bin/webscr' method="post"  > 
	<input type="hidden" name="cmd" value="_cart"> 
	<input type="hidden" name="upload" value="1"> 
	<input type="hidden" name="business" value="bmindf_1290779949_biz@gmail.com"> 
	<input type="hidden" id="item_name_1" name="item_name_1" value="album"> 
	<input type="hidden" id="amount_1" name="amount_1" value="5">
	<input type="hidden" id="quantity_1" name="quantity_1" value="2">
	
	<input type="hidden" id='return' name="return" value="http://localhost:3000/checkout">
	<input type="hidden" name="cancel_return" value='http://localhost:3000/checkout'>
	<input type="hidden" name="notify_url" value="http://localhost:3000/checkout">
	<input type="hidden" id="currency_code" name="currency_code" value="USD" />
	<input type='submit'>
</form>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>