config/routes.rb
InventoryManagement::Application.routes.draw do

  resources :private_orders

  resources :invoices

  resources :cart_items

  resources :orders

  resources :customers

	resources :artists

	resources :albums

	resources :users
	
	resources :public, :only => [:list, :show, :add_to_cart, :show_cart, :empty_cart, :remove_item, :checkout, :save_order, :report]
	resources :private, :only => [:list, :add_private_cart, :private_showcart, :remove_private_item, :empty_private_cart, :show_private_checkout, :save_private_order, :private_report]
	resources :sessions, :only => [:new, :create, :destroy]

	match '/', :to => 'pages#home'
	
	match '/signup', :to => 'users#new'
	match '/home', :to => 'users#home' 
	match '/testmail' => 'users#mail'
	
	match '/list', :to => 'public#list'
	match '/showalbum', :to => 'public#showalbum'
	match '/addtocart', :to => 'public#add_to_cart'
	match '/showcart', :to => 'public#show_cart'
	match '/emptycart', :to => 'public#empty_cart'
	match '/removeitem', :to => 'public#remove_item'
	match '/checkout', :to => 'public#checkout'
  match '/saveorder', :to => 'public#save_order'
  match '/report', :to => 'public#report'
	
  match '/privatealbums', :to => 'private#list'
  match '/addprivatecart', :to => 'private#add_private_cart'
  match '/privateshowcart', :to => 'private#private_showcart'
  match '/removeprivateitem', :to => 'private#remove_private_item'
  match '/emptyprivatecart', :to => 'private#empty_private_cart'
  match '/privatecheckout', :to => 'private#private_checkout'
  match '/showprivatecheckout', :to => 'private#show_private_checkout'
  match '/saveprivateorder', :to => 'private#save_private_order'
  match '/privatereport/:invoice' => 'private#private_report'

  
	match '/signin', :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'
	
	root :to => 'pages#home'
	
	
	

end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :album
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  # GET /cart_items
  # GET /cart_items.xml
  def index
    @cart_items = CartItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cart_items }
    end
  end

  # GET /cart_items/1
  # GET /cart_items/1.xml
  def show
    @cart_item = CartItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cart_item }
    end
  end

  # GET /cart_items/new
  # GET /cart_items/new.xml
  def new
    @cart_item = CartItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cart_item }
    end
  end

  # GET /cart_items/1/edit
  def edit
    @cart_item = CartItem.find(params[:id])
  end

  # POST /cart_items
  # POST /cart_items.xml
  def create
    @cart_item = CartItem.new(params[:cart_item])

    respond_to do |format|
      if @cart_item.save
        format.html { redirect_to(@cart_item, :notice => 'Cart item was successfully created.') }
        format.xml  { render :xml => @cart_item, :status => :created, :location => @cart_item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cart_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cart_items/1
  # PUT /cart_items/1.xml
  def update
    @cart_item = CartItem.find(params[:id])

    respond_to do |format|
      if @cart_item.update_attributes(params[:cart_item])
        format.html { redirect_to(@cart_item, :notice => 'Cart item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cart_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cart_items/1
  # DELETE /cart_items/1.xml
  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy

    respond_to do |format|
      format.html { redirect_to(cart_items_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/_form.html.erb
<%= form_for(@cart_item) do |f| %>
  <% if @cart_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart_item.errors.count, "error") %> prohibited this cart_item from being saved:</h2>

      <ul>
      <% @cart_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cart_items/edit.html.erb
<h1>Editing cart_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart_item %> |
<%= link_to 'Back', cart_items_path %>

app/views/cart_items/index.html.erb
<h1>Listing cart_items</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cart_items.each do |cart_item| %>
  <tr>
    <td><%= link_to 'Show', cart_item %></td>
    <td><%= link_to 'Edit', edit_cart_item_path(cart_item) %></td>
    <td><%= link_to 'Destroy', cart_item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart item', new_cart_item_path %>

app/views/cart_items/new.html.erb
<h1>New cart_item</h1>

<%= render 'form' %>

<%= link_to 'Back', cart_items_path %>

app/views/cart_items/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_cart_item_path(@cart_item) %> |
<%= link_to 'Back', cart_items_path %>