config/routes.rb
InventoryManagement::Application.routes.draw do

  resources :private_orders

  resources :invoices

  resources :cart_items

  resources :orders

  resources :customers

	resources :artists

	resources :albums

	resources :users
	
	resources :public, :only => [:list, :show, :add_to_cart, :show_cart, :empty_cart, :remove_item, :checkout, :save_order, :report]
	resources :private, :only => [:list, :add_private_cart, :private_showcart, :remove_private_item, :empty_private_cart, :show_private_checkout, :save_private_order, :private_report]
	resources :sessions, :only => [:new, :create, :destroy]

	match '/', :to => 'pages#home'
	
	match '/signup', :to => 'users#new'
	match '/home', :to => 'users#home' 
	match '/testmail' => 'users#mail'
	
	match '/list', :to => 'public#list'
	match '/showalbum', :to => 'public#showalbum'
	match '/addtocart', :to => 'public#add_to_cart'
	match '/showcart', :to => 'public#show_cart'
	match '/emptycart', :to => 'public#empty_cart'
	match '/removeitem', :to => 'public#remove_item'
	match '/checkout', :to => 'public#checkout'
  match '/saveorder', :to => 'public#save_order'
  match '/report', :to => 'public#report'
	
  match '/privatealbums', :to => 'private#list'
  match '/addprivatecart', :to => 'private#add_private_cart'
  match '/privateshowcart', :to => 'private#private_showcart'
  match '/removeprivateitem', :to => 'private#remove_private_item'
  match '/emptyprivatecart', :to => 'private#empty_private_cart'
  match '/privatecheckout', :to => 'private#private_checkout'
  match '/showprivatecheckout', :to => 'private#show_private_checkout'
  match '/saveprivateorder', :to => 'private#save_private_order'
  match '/privatereport/:invoice' => 'private#private_report'

  
	match '/signin', :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'
	
	root :to => 'pages#home'
	
	
	

end

app/views/layouts/_header.html.erb
<style>
ul {
list-style-type: none;
margin: auto;
}
li{
	float:left
}
ul a {
padding-right: 32px;
padding-left: 32px;
text-decoration: none;
font-family: Georgia, "Times New Roman", Times, serif;
font-size: 21px;
color: #371C1C;
}	
.header{
	float:left;
	width:100%;
}
.yield{
	float:left;
}
</style>
<div class='header'>

<%= session[:id] %>
	<ul class='header'>
		<li><%= link_to "Home", root_path %></li>
		<% if signed_in? %>
			
			<% if session[:user_type] == 'admin' %>
				<li><%= link_to "Users", users_path %></li>
				<li><%= link_to "Albums", albums_path %></li>
				<li><%= link_to "Artists", artists_path %></li>
				<li><%= link_to "Customer", customers_path %></li>
				<li><%= link_to "Order", orders_path %></li>
			<% else %>
				<li><%= link_to "Albums", privatealbums_path %></li>			
			<% end %>
			<li><%= link_to "Settings", edit_user_path(current_user) %></li>
			<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
		<% else %>
			<li><%= link_to "list", list_path %></li>
			<li><%= link_to "Sign in", signin_path %></li>
			<li><%= link_to "Sign up now!", signup_path %></li>
		<% end %> 
	</ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
			<title>InventoryManagement</title>
			<%= stylesheet_link_tag :all %>
			<%= javascript_include_tag :all %>
			<!-- <%= csrf_meta_tag %> -->
	</head>
	<body>
		<div class="container">
			<%= render 'layouts/header' %>
			
			<% flash.each do |key, value| %>
				<div class="flash <%= key %>"><%= value %></div>
			<% end %>
			<div class='yield'>
			<%= yield %>
			</div>
		</div>
	</body>
</html>